SELECT
    AU.AUTHOR_ID
    ,AU.AUTHOR_NAME
    ,BO.CATEGORY
    ,SUM(BO.PRICE * BS.SALES) AS TOTAL_SALES
FROM
    BOOK AS BO
JOIN
    AUTHOR AS AU
ON
    BO.AUTHOR_ID = AU.AUTHOR_ID
JOIN
    BOOK_SALES AS BS
ON
    BO.BOOK_ID = BS.BOOK_ID
WHERE
    YEAR(BS.SALES_DATE) = 2022 AND
    MONTH(BS.SALES_DATE) = 1
GROUP BY
    AU.AUTHOR_ID
    ,BO.CATEGORY
ORDER BY
    AU.AUTHOR_ID ASC
    ,BO.CATEGORY DESC