WITH TOP_FAV_REST AS 
(
    SELECT
        FOOD_TYPE
        ,MAX(FAVORITES) AS FAVORITES
    FROM
        REST_INFO
    GROUP BY
        FOOD_TYPE
)

SELECT
    REST_INFO.FOOD_TYPE
    ,REST_INFO.REST_ID
    ,REST_INFO.REST_NAME
    ,REST_INFO.FAVORITES
FROM
    REST_INFO
INNER JOIN
    TOP_FAV_REST
ON
    REST_INFO.FAVORITES = TOP_FAV_REST.FAVORITES
        GROUP BY
        FOOD_TYPE
ORDER BY
    FOOD_TYPE DESC
        