SELECT
    YEAR(SALES_DATE) AS YEAR
    ,MONTH(SALES_DATE) AS MONTH
    ,UI.GENDER
    ,COUNT(DISTINCT UI.USER_ID) AS USERS
FROM
    USER_INFO AS UI
JOIN
    ONLINE_SALE AS OS
ON
    UI.USER_ID = OS.USER_ID
WHERE
    GENDER IS NOT NULL
GROUP BY
    1, 2, 3
ORDER BY
    1, 2, 3