WITH UI2021 AS (
    SELECT
        USER_ID
    FROM
        USER_INFO
    WHERE
        YEAR(JOINED) = 2021
)

SELECT
    YEAR(OS.SALES_DATE) AS YEAR
    ,MONTH(OS.SALES_DATE) AS MONTH
    ,COUNT(DISTINCT OS.USER_ID) AS PUCHASED_USERS
    ,ROUND(COUNT(DISTINCT OS.USER_ID) / (SELECT COUNT(DISTINCT UI2021.USER_ID) FROM UI2021), 1) AS PUCHASED_RATIO
FROM
    USER_INFO AS UI
LEFT JOIN
    UI2021
ON
    UI2021.USER_ID = UI.USER_ID
RIGHT JOIN
    ONLINE_SALE AS OS
ON
    OS.USER_ID = UI.USER_ID
WHERE
    UI2021.USER_ID IS NOT NULL
GROUP BY
    MONTH
ORDER BY
    MONTH ASC