SELECT 
    CRH.HISTORY_ID
    ,CAST(
        ROUND(
            CRC.DAILY_FEE * 
            (DATEDIFF(CRH.END_DATE, CRH.START_DATE) + 1) * 
            CASE
                WHEN DATEDIFF(CRH.END_DATE, CRH.START_DATE) + 1 >= 90 THEN (1 - CRP.DISCOUNT_RATE * 0.01)
                WHEN DATEDIFF(CRH.END_DATE, CRH.START_DATE) + 1 >= 30 THEN (1 - CRP.DISCOUNT_RATE * 0.01)
                WHEN DATEDIFF(CRH.END_DATE, CRH.START_DATE) + 1 >= 7 THEN (1 - CRP.DISCOUNT_RATE * 0.01)
                ELSE 1
            END
        ,0) AS UNSIGNED
    ) AS FEE
FROM 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CRH

JOIN 
    CAR_RENTAL_COMPANY_CAR AS CRC 
ON 
    CRH.CAR_ID = CRC.CAR_ID

LEFT JOIN 
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS CRP 
ON 
    CRC.CAR_TYPE = CRP.CAR_TYPE AND (
        (DATEDIFF(CRH.END_DATE, CRH.START_DATE) + 1 >= 7 AND CRP.DURATION_TYPE = '7일 이상') OR
        (DATEDIFF(CRH.END_DATE, CRH.START_DATE) + 1 >= 30 AND CRP.DURATION_TYPE = '30일 이상') OR
        (DATEDIFF(CRH.END_DATE, CRH.START_DATE) + 1 >= 90 AND CRP.DURATION_TYPE = '90일 이상')
    )

WHERE 
    CRC.CAR_TYPE = '트럭'

GROUP BY 
    CRH.HISTORY_ID

ORDER BY 
    FEE DESC
    ,CRH.HISTORY_ID DESC