SELECT
    AP.APNT_NO
    ,PT.PT_NAME
    ,PT.PT_NO
    ,AP.MCDP_CD
    ,DO.DR_NAME
    ,AP.APNT_YMD
FROM
    APPOINTMENT AS AP
INNER JOIN
    DOCTOR AS DO
ON
    AP.MDDR_ID = DO.DR_ID
INNER JOIN
    PATIENT AS PT
ON
    AP.PT_NO = PT.PT_NO
WHERE
    YEAR(AP.APNT_YMD) = 2022 AND
    MONTH(AP.APNT_YMD) = 4 AND
    DAY(AP.APNT_YMD) = 13 AND
    AP.APNT_CNCL_YN = 'N'
ORDER BY
    APNT_YMD ASC