WITH MAX_COLONY_DATA AS 
(
    SELECT
        YEAR(DIFFERENTIATION_DATE) AS YEAR
        ,MAX(SIZE_OF_COLONY) AS MAX_COLONY
    FROM
        ECOLI_DATA
    GROUP BY
        YEAR
)

SELECT
    MAX_COLONY_DATA.YEAR
    ,(MAX_COLONY_DATA.MAX_COLONY - ECOLI_DATA.SIZE_OF_COLONY) AS YEAR_DEV
    ,ECOLI_DATA.ID
FROM
    MAX_COLONY_DATA
JOIN
    ECOLI_DATA
ON
    YEAR(ECOLI_DATA.DIFFERENTIATION_DATE) = MAX_COLONY_DATA.YEAR
ORDER BY
    MAX_COLONY_DATA.YEAR ASC, YEAR_DEV ASC