SELECT DISTINCT
    CONCAT('/home/grep/src/', UB.BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM
    USED_GOODS_BOARD AS UB
JOIN
    USED_GOODS_FILE AS UF
ON
    UB.BOARD_ID = UF.BOARD_ID
JOIN
    (SELECT BOARD_ID FROM USED_GOODS_BOARD ORDER BY VIEWS DESC LIMIT 1) AS A
ON
    UB.BOARD_ID = A.BOARD_ID 
ORDER BY
    UF.FILE_ID DESC